### ISSUE TITLE
Scheduler and Timetable capabilities

### ISSUE THREAD

**Issue by CodingAviator** [Epicalable/JARVIS#5]
Whenever we think of a computer program designed to talk to you we would also want it to be helpful to us by telling us things to do or upcoming work/project deadlines and motivate us to do things.
Jarvis will always need new features to keep it ahead of it's competitors and our job is to make it more interactive as possible.

**Comment by Mahadhevha** [comment]
Acknowledged and will start working on it ASAP.

**Comment by Mahadhevha** [comment]
Commit 188cff7 has added task function to JARVIS. Meaning you will be able to create tasks and will be able to track what outstanding work you have. This is currently assessable in the GUI's Menu drop box.
We still have some more work to be done like adding a timer to each task and also try to add a timetable if possible (along with a Calander).
Thank You ALL.

**Comment by CodingAviator** [comment]
Thank you for the contribution. We will help to ensure this project is equipped with the best functions python could ever offer.
