### ISSUE TITLE
Re-structuring the RENDER-WORD Engine.

### ISSUE THREAD

**Issue by Mahadhevha** [Epicalable/JARVIS#6]
As new words and output options are being added commit to commit it is important to make sure all the output are being shown correctly without any errors or mixing up the output.
This is why it is important to come up with a new system to help the program select outputs easier.
Example: When user says 'Hi' JARVIS will say 'Hello Sir', But now if the user says 'Dolphin' JARVIS will say 'Hello Sir'.
Even though Dolphin is an option in 'Jarindents.json' file JARVIS will come up with another output. 
We cannot afford to turn a blind eye to this problem as soon when we want to expand JARVIS's vocabulary we would run into many more problems.
Thank You.

**Comment by CodingAviator** [comment]
Thanks for the heads up on an incoming problem. It is better to overcome this issue now then when things hit the roof. We will work on resolving this issue by the next few commits. 
The render word engine was created by Epicalable research and development team to help sort out inputs to its designated outputs. We will raise this issue for them to settle.
Thanks all for raising this issue.

**Comment by EpicRD** [comment]
As part of the research and development department I will do my best to bring in a new algorithm and implement it for a smoother and more efficient way of output searching.
Thanks all

**Comment by SimonRogers3** [comment]
Hi

**Comment by EpicRD** [comment]
As per the latest commit 5930fa31 we have tweaked the engine to help distinguish words with the help of spaces so it would not mix up a full word like dolphin with a word in-between like hi.
We will continue to monitor the issue and will close this issue once there is no more problems.
Once done R&D will finally go back to jardash hehehe.
Thanks all

**Comment by Mahadhevha** [comment]
Thanks for taking the time to help fix and make the engine more flexible.
The coding department will monitor for any errors raised in the future and will work on them asap.

**Comment by Mahadhevha** [comment]
current progress is on a stalemate.
