### ISSUE TITLE
Flight Tracker Issue Tracker

### ISSUE THREAD

**Issue by Mahadhevha** [Epicalable/JARVIS#7]
Currently this function is in beta and is currently under testing. 
We will also be trying to create a GUI to show the data rather than on the mainframe terminal.
R&D and Coding Department will help to oversee this function's issues and will close this issue once all problems are rectified and solved.

**Comment by Mahadhevha** [comment]
Just realised we can make a dedicated menu to get data that the user wants at the moment such as stocks and now flight number.
Don’t know just an idea for the frontend so it easier at the backend to keep track of the values and data flow.
Thank you

**Comment by EpicRD** [comment]
Thank you for helping out in integrating the API and our framework to the code. I will come out with a better algorithm to help extract data from complex json structures in the coming days.
Thank you
